"global":
  "projectName": "infrastructure-charts"
  "source":
    "appsBasePath": "stages/dev/infrastructure-charts/apps"
    "repoURL": "https://gitlab.infrastructure-mdoc.iits.tech/mdoc/devops/infrastructure-charts.git"
    "targetRevision": "main"
  "stage": "dev"
  chartPath: "apps"
  helmValues:
    - name: stage
      value: $STAGE
    - name: dns.host
      value: "admin.beri-$STAGE.guardians-of-the-otc.com"
argocd-config:
  namespace: argocd
cert-manager:
  namespace: cert-manager
traefik:
  namespace: routing
  helmValues:
    - name: "traefik.deployment.replicas"
      value: "1"
storage-classes:
  namespace: storage
admin-dashboard:
  namespace: admin
kafka:
  namespace: kafka
basic-auth-gateway:
  namespace: routing